# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-04-14 16:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumni',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=200)),
                ('ortId', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AlumniLesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField(default=0)),
                ('alumni', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simpleapp.Alumni')),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Отделение')),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='faculty',
            name='lessons',
            field=models.ManyToManyField(to='simpleapp.Lesson'),
        ),
        migrations.AddField(
            model_name='alumnilesson',
            name='lesson',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='simpleapp.Lesson'),
        ),
        migrations.AddField(
            model_name='alumni',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simpleapp.Faculty'),
        ),
        migrations.AddField(
            model_name='alumni',
            name='tour',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='simpleapp.Tour'),
        ),
    ]
