# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-05-03 21:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simpleapp', '0002_faculty_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumni',
            name='extra_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='alumni',
            name='summa',
            field=models.IntegerField(default=0),
        ),
    ]
