# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-05-03 21:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simpleapp', '0003_auto_20170504_0301'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumni',
            name='barcode',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='alumni',
            name='place',
            field=models.CharField(choices=[('Шаар', 'Шаар'), ('Борбор', 'Борбор'), ('Айыл', 'Айыл'), ('Тоо', 'Тоо')], max_length=100, null=True),
        ),
    ]
