# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-05-03 21:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simpleapp', '0004_auto_20170504_0305'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumni',
            name='main',
            field=models.IntegerField(default=0),
        ),
    ]
