# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-05-03 21:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simpleapp', '0005_alumni_main'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumni',
            name='phone',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
