# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-05-03 22:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simpleapp', '0006_alumni_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumni',
            name='faculty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='simpleapp.Faculty'),
        ),
    ]
