# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-05-03 23:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simpleapp', '0007_auto_20170504_0454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumnilesson',
            name='alumni',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='simpleapp.Alumni'),
        ),
    ]
