# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-06-15 08:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simpleapp', '0008_auto_20170504_0533'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumni',
            name='fio',
        ),
        migrations.AddField(
            model_name='tour',
            name='final',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='initial',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
