# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-06-15 13:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('simpleapp', '0009_auto_20170615_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumni',
            name='atestat',
            field=models.BooleanField(default=datetime.datetime(2017, 6, 15, 13, 30, 6, 156787, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alumni',
            name='lgotnik',
            field=models.BooleanField(default=datetime.datetime(2017, 6, 15, 13, 30, 15, 846175, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
