# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-06-15 13:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simpleapp', '0010_auto_20170615_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumni',
            name='atestat',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='alumni',
            name='lgotnik',
            field=models.BooleanField(default=False),
        ),
    ]
