# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-06-15 19:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simpleapp', '0011_auto_20170615_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='filled_quota',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='faculty',
            name='quota',
            field=models.IntegerField(default=0),
        ),
    ]
