# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-06-16 05:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simpleapp', '0012_auto_20170616_0129'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumni',
            name='olimpiadnik',
            field=models.BooleanField(default=False),
        ),
    ]
