# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-06-16 08:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import simpleapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('simpleapp', '0013_alumni_olimpiadnik'),
    ]

    operations = [
        migrations.CreateModel(
            name='Protocol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otchet', models.FileField(blank=True, null=True, upload_to=simpleapp.models.file_upload_to)),
                ('protocol', models.FileField(blank=True, null=True, upload_to=simpleapp.models.file_upload_to)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='simpleapp.Faculty')),
                ('tour', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='simpleapp.Tour')),
            ],
        ),
    ]
