# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-06-16 08:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import simpleapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('simpleapp', '0014_protocol'),
    ]

    operations = [
        migrations.CreateModel(
            name='Otchet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otchet', models.FileField(blank=True, null=True, upload_to=simpleapp.models.file_upload_to)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='simpleapp.Faculty')),
                ('tour', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='simpleapp.Tour')),
            ],
        ),
        migrations.RemoveField(
            model_name='protocol',
            name='department',
        ),
        migrations.RemoveField(
            model_name='protocol',
            name='tour',
        ),
        migrations.AddField(
            model_name='alumni',
            name='passed',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Protocol',
        ),
    ]
